# -*- coding: utf-8 -*-
"""Dashbroadsu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHzQvrvEEMfs2V2YByw7CqW6vZJteFDZ
"""

import streamlit as st
import pandas as pd

# Load data
df = pd.read_csv("Merge Data Excel - Sheet1 (1).csv")

# Ubah kolom tanggal ke datetime
df['Tanggal Transaksi Terakhir'] = pd.to_datetime(df['Tanggal Transaksi Terakhir'], errors='coerce')

# Tambahkan kolom Tahun dan Bulan
df['Tahun'] = df['Tanggal Transaksi Terakhir'].dt.year
df['Bulan'] = df['Tanggal Transaksi Terakhir'].dt.month

# Konversi kolom saldo ke numerik
saldo_cols = [
    'Saldo Telah Menjadi Hak Negara',
    'Saldo Rekening Antara untuk menampung pembayaran dari negara',
    'Saldo Belum/tidak menjadi hak negara'
]

for col in saldo_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Streamlit UI
st.title("Dashboard Rekap KPPN")

# Sidebar filter
st.sidebar.header("Filter Waktu")
selected_year = st.sidebar.selectbox("Pilih Tahun", sorted(df['Tahun'].dropna().unique()))
selected_month = st.sidebar.selectbox("Pilih Bulan", sorted(df['Bulan'].dropna().unique()))

# Filter data
filtered_df = df[(df['Tahun'] == selected_year) & (df['Bulan'] == selected_month)]

# Hitung total saldo
saldo_hak_negara = filtered_df['Saldo Telah Menjadi Hak Negara'].sum()
saldo_rek_antara = filtered_df['Saldo Rekening Antara untuk menampung pembayaran dari negara'].sum()
saldo_belum_hak = filtered_df['Saldo Belum/tidak menjadi hak negara'].sum()

# Tampilkan metrik dalam 3 kotak
col1, col2, col3 = st.columns(3)
col1.metric("Saldo Telah Menjadi Hak Negara", f"Rp {saldo_hak_negara:,.0f}")
col2.metric("Saldo Rekening Antara", f"Rp {saldo_rek_antara:,.0f}")
col3.metric("Saldo Belum Menjadi Hak Negara", f"Rp {saldo_belum_hak:,.0f}")

# Tampilkan tabel
st.subheader("Detail Data")
st.dataframe(filtered_df)

