# -*- coding: utf-8 -*-
"""Dashbroadsu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHzQvrvEEMfs2V2YByw7CqW6vZJteFDZ
"""

import streamlit as st
import pandas as pd

# Load data
df = pd.read_csv("Merge Datas.csv")

# Ubah kolom tanggal ke datetime
df['Tanggal Transaksi Terakhir'] = pd.to_datetime(df['Tanggal Transaksi Terakhir'], errors='coerce')

# Tambahkan kolom Tahun dan Bulan
df['Tahun'] = df['Tanggal Transaksi Terakhir'].dt.year
df['Bulan'] = df['Tanggal Transaksi Terakhir'].dt.month

# Konversi kolom saldo ke numerik
saldo_cols = [
    'Saldo Telah Menjadi Hak Negara',
    'Saldo Rekening Antara untuk menampung pembayaran dari negara',
    'Saldo Belum/tidak menjadi hak negara'
]

for col in saldo_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Streamlit UI
st.title("📊 Dashboard Rekap KPPN")

# Sidebar filter
st.sidebar.header("🔍 Filter Data")
available_years = sorted(df['Tahun'].dropna().unique())
selected_year = st.sidebar.selectbox("Pilih Tahun", available_years)

# Filter bulan berdasarkan tahun yang dipilih
available_months = sorted(df[df['Tahun'] == selected_year]['Bulan'].dropna().unique())
selected_month = st.sidebar.selectbox("Pilih Bulan", available_months)

# Filter data
filtered_df = df[(df['Tahun'] == selected_year) & (df['Bulan'] == selected_month)]

# Fungsi format rupiah
def format_rupiah(x):
    if pd.isna(x):
        return "Rp 0"
    return f"Rp {x:,.0f}".replace(",", ".")

# Ambil nilai baris pertama (bukan jumlah)
if not filtered_df.empty:
    first_row = filtered_df.iloc[0]
    saldo_hak_negara = first_row['Saldo Telah Menjadi Hak Negara']
    saldo_rek_antara = first_row['Saldo Rekening Antara untuk menampung pembayaran dari negara']
    saldo_belum_hak = first_row['Saldo Belum/tidak menjadi hak negara']
else:
    saldo_hak_negara = saldo_rek_antara = saldo_belum_hak = 0

# Tampilkan metrik
col1, col2, col3 = st.columns(3)
col1.metric("Saldo Telah Menjadi Hak Negara", format_rupiah(saldo_hak_negara))
col2.metric("Saldo Rekening Antara", format_rupiah(saldo_rek_antara))
col3.metric("Saldo Belum Menjadi Hak Negara", format_rupiah(saldo_belum_hak))

# Tampilkan tabel detail
st.subheader("📄 Tabel Data Filtered")
st.dataframe(filtered_df)

